### ISSUE TITLE
有报错？

### ISSUE THREAD

**Issue by muyi137** [xiaobaiaixibai/Real-time-visualization-of-national-news#2]
"C:\Program Files\Python310\python.exe" E:/www/yd/python/Real-time-visualization-of-national-news-main/xinhua/test.py
Traceback (most recent call last):
  File "E:\www\yd\python\Real-time-visualization-of-national-news-main\xinhua\test.py", line 8, in <module>
    from xinhua.spiders.guangmingspider import GuangmingspiderSpider
  File "E:\www\yd\python\Real-time-visualization-of-national-news-main\xinhua\xinhua\spiders\guangmingspider.py", line 4, in <module>
    from scrapy_splash import SplashRequest
ModuleNotFoundError: No module named 'scrapy_splash'

**Comment by xiaobaiaixibai** [comment]
有几个网站scrapy反爬有点问题，所以有些网站使用了splash进行爬取，可以将splash那段代码删除或者你可以去下载一个splash镜像，删除splash那段代码只是有些网站爬取信息会减少，不会导致其他问题

**Comment by muyi137** [comment]
好了
